# Generated by Django 3.0.6 on 2020-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('esname', models.CharField(max_length=40)),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
